data_provider_id: transaction
id: Transaction
flat:
  Total: Decimal(10,2)
  Status: Enum('Pending,Successful,Failed,Dispatched,Processing,Cancelled','Pending')
  Currency: Varchar(5)
related:
parent:
children:
  