---
Name: ecommerceroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'ecommerce': 'Heystack\Ecommerce\Controller\InputController'

Heystack\Ecommerce\Controller\InputController:
  url_handlers:
    'input//$Action/$Processor/$ID/$OtherID/$ExtraID': '$Action'
  allowed_actions:
    - 'process'