parameters:
  
  currency_service.class: Heystack\Subsystem\Ecommerce\Currency\CurrencyService
  currency_subscriber.class: Heystack\Subsystem\Ecommerce\Currency\Subscriber
  currency_input_processor.class: Heystack\Subsystem\Ecommerce\Currency\Input\Processor
  currency_output_processor.class: Heystack\Subsystem\Ecommerce\Currency\Output\Processor
  currency.class: $$$
  
  locale_service.class: Heystack\Subsystem\Ecommerce\Locale\LocaleService
  country.class: $$$
    
  transaction.class: Heystack\Subsystem\Ecommerce\Transaction\Transaction
  
  transaction.statuses: [ 'Pending', 'Successful', 'Failed', 'Dispatched', 'Processing', 'Cancelled' ]
  
  transaction.default: Pending
  
  transaction_subscriber.class: Heystack\Subsystem\Ecommerce\Transaction\Subscriber
  
  collator.class: Heystack\Subsystem\Ecommerce\Transaction\Collator
  
services:
  
  transaction:
    class: %transaction.class%
    arguments: [ @state, %collator.class%, @currency_service, %transaction.statuses%, %transaction.default% ]
    calls:
      - [ restoreState ]
    tags:
      - { name: ss_orm_backend.data_provider }
      
  transaction_subscriber:
    class: %transaction_subscriber.class%
    arguments: [ @transaction, @event_dispatcher, @storage, @state ]
    tags:
      - { name: event_dispatcher.subscriber }
    
  locale_service:
    class: %locale_service.class%
    arguments: [ %country.class%, @state, @state_global, @event_dispatcher, @monolog ]
    calls:
      - [ restoreGlobalState ]
      - [ restoreState ]
    
  currency_service:
    class: %currency_service.class%
    arguments: [ %currency.class%, @state,  @state_global, @event_dispatcher ]
    calls:
      - [ restoreGlobalState ]
      - [ restoreState ]
  
  currency_subscriber:
    class: %currency_subscriber.class%
      
  currency_input_processor:
    class: %currency_input_processor.class%
    arguments: [ %currency.class%, @currency_service ]
    tags:
      - { name: input_processor_handler.processor }
    
  currency_output_processor:
    class: %currency_output_processor.class%
    arguments: [%currency.class%]    
    tags:
      - { name: output_processor_handler.processor }
      
  transaction_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-core/config/storage/transaction.yml, @state_global ]
    tags:
      - { name: dataobject_generator.schema }      