parameters:
  
  currency_subscriber.class: Heystack\Subsystem\Ecommerce\Currency\Subscriber
  currency_input_processor.class: Heystack\Subsystem\Ecommerce\Currency\Input\Processor
  currency_output_processor.class: Heystack\Subsystem\Ecommerce\Currency\Output\Processor
  currency.class: EcommerceCurrency
  currency_service.class: Heystack\Subsystem\Ecommerce\Currency\CurrencyService
  
  purchasable_subscriber.class: Heystack\Subsystem\Ecommerce\Purchasable\Subscriber
  
services:
  
  currency_service:
    class: %currency_service.class%
    arguments: [@state, @event_dispatcher]
  
  currency_subscriber:
    class: %currency_subscriber.class%
      
  purchasable_subscriber:
    class: %purchasable_subscriber.class%

  event_dispatcher:
    calls: 
      - [ addSubscriber, [ @currency_subscriber ] ]
      - [ addSubscriber, [ @purchasable_subscriber ] ]
      
  currency_input_processor:
    class: %currency_input_processor.class%
    arguments: [%currency.class%,@currency_service]
    
  currency_output_processor:
    class: %currency_output_processor.class%
    arguments: [%currency.class%]    
      
  input_processor_handler:
    calls:
      - [ addProcessor, [ @currency_input_processor ] ]
      
  output_processor_handler:
    calls:
      - [ addProcessor, [ @currency_output_processor ] ]
      