parameters:
  
  currency_subscriber.class: Heystack\Subsystem\Ecommerce\Currency\Subscriber
  currency_processor.class: Heystack\Subsystem\Ecommerce\Currency\Processor
  
  purchaseable_subscriber.class: Heystack\Subsystem\Ecommerce\Purchaseable\Subscriber
  
services:
  
  currency_subscriber:
    class: %currency_subscriber.class%
      
  purchaseable_subscriber:
    class: %purchaseable_subscriber.class%

  event_dispatcher:
    calls: 
      - [ addSubscriber, [ @currency_subscriber ] ]
      - [ addSubscriber, [ @purchaseable_subscriber ] ]
      
  currency_processor:
    class: %currency_processor.class%
    arguments: [@state, @event_dispatcher]
      
  processor_handler:
    calls:
      - [ addProcessor, [ @currency_processor ] ]
