parameters:
  
  currency_subscriber.class: Heystack\Subsystem\Ecommerce\Currency\Subscriber
  currency_input_processor.class: Heystack\Subsystem\Ecommerce\Currency\Input\Processor
  currency_output_processor.class: Heystack\Subsystem\Ecommerce\Currency\Output\Processor
  currency.class: EcommerceCurrency
  
  currency_service.class: Heystack\Subsystem\Ecommerce\Currency\CurrencyService
  
  purchasable_subscriber.class: Heystack\Subsystem\Ecommerce\Purchasable\Subscriber
  
  transaction.class: Heystack\Subsystem\Ecommerce\Transaction\Transaction
  
  transaction_subscriber.class: Heystack\Subsystem\Ecommerce\Transaction\Subscriber
  
services:
  
  transaction:
    class: %transaction.class%
    arguments: [ @state ]
    calls:
      - [ restoreState ]
      
  transaction_subscriber:
    class: %transaction_subscriber.class%
    arguments: [ @transaction, @event_dispatcher, @storage_processor_handler ]
    
  currency_service:
    class: %currency_service.class%
    arguments: [ %currency.class%, @state, @event_dispatcher ]
    calls:
      - [ restoreState ]
  
  currency_subscriber:
    class: %currency_subscriber.class%
      
  purchasable_subscriber:
    class: %purchasable_subscriber.class%
      
  currency_input_processor:
    class: %currency_input_processor.class%
    arguments: [ %currency.class%, @currency_service ]
    
  currency_output_processor:
    class: %currency_output_processor.class%
    arguments: [%currency.class%]    
      
  input_processor_handler:
    class: %input_processor_handler.class%
    calls:
      - [ addProcessor, [ @currency_input_processor ] ]
      
  output_processor_handler:
    class: %output_processor_handler.class%
    calls:
      - [ addProcessor, [ @currency_output_processor ] ]
      
  event_dispatcher:
    class: %event_dispatcher.class%
    calls: 
      - [ addSubscriber, [ @transaction_subscriber ] ]
  
  dataobject_generator:
    class: %dataobject_generator.class%
    calls:
      - [ addYamlSchema, [ ecommerce-core/config/storage/transaction.yml ] ]
      
      