parameters:
  currency_service.class: Heystack\Ecommerce\Currency\CurrencyService
  currency_subscriber.class: Heystack\Ecommerce\Currency\Subscriber
  currency_input_processor.class: Heystack\Ecommerce\Currency\Input\Processor
  currency_output_processor.class: Heystack\Ecommerce\Currency\Output\Processor
  locale_service.class: Heystack\Ecommerce\Locale\LocaleService
  transaction.class: Heystack\Ecommerce\Transaction\Transaction
  transaction.statuses: [ 'Pending', 'Successful', 'Failed', 'Dispatched', 'Processing', 'Cancelled' ]
  transaction.default: Pending
  transaction_subscriber.class: Heystack\Ecommerce\Transaction\Subscriber
  transaction_collator.class: Heystack\Ecommerce\Transaction\Collator

services:
  transaction:
    class: %transaction.class%
    arguments:
      2: %transaction.statuses%
      3: %transaction.default%
    tags:
      - { name: state.restore }
      - { name: autoinject, all: true }
      - { name: autoinject.provides, all: true }

  transaction_subscriber:
    class: %transaction_subscriber.class%
    tags:
      - { name: event_dispatcher.subscriber }
      - { name: autoinject, all: true }
      
  transaction_collator:
    class: %transaction_collator.class%
    tags:
      - { name: autoinject.provides, all: true }
      - { name: autoinject, arguments: true }

  locale_service:
    class: %locale_service.class%
    arguments: [ [], null ]
    tags:
      - { name: state.restore }
      - { name: autoinject, arguments: true }
      - { name: autoinject.provides, all: true }

  currency_service:
    class: %currency_service.class%
    arguments: [ [], null ]
    tags:
      - { name: state.restore }
      - { name: autoinject, arguments: true }
      - { name: autoinject.provides, all: true }

  currency_subscriber:
    class: %currency_subscriber.class%

  currency_input_processor:
    class: %currency_input_processor.class%
    arguments: [ 'currency' ]
    tags:
      - { name: autoinject, arguments: true }
      - { name: autoinject.provides, arguments: true }

  currency_output_processor:
    class: %currency_output_processor.class%
    arguments: [ 'currency' ]
    tags:
      - { name: output_processor_handler.processor }
      - { name: autoinject.provides, arguments: true }

  transaction_schema:
    class: %yaml_data_object_schema.class%
    arguments: [ ecommerce-core/config/storage/transaction.yml ]
    tags:
      - { name: schema }
      - { name: autoinject, arguments: true }
    
