parameters:
  
  currency_subscriber.class: Heystack\Subsystem\Ecommerce\Currency\Subscriber
  currency_processor.class: Heystack\Subsystem\Ecommerce\Currency\Processor
  
  purchasable_subscriber.class: Heystack\Subsystem\Ecommerce\Purchasable\Subscriber
  
services:
  
  currency_subscriber:
    class: %currency_subscriber.class%
      
  purchasable_subscriber:
    class: %purchasable_subscriber.class%

  event_dispatcher:
    calls: 
      - [ addSubscriber, [ @currency_subscriber ] ]
      - [ addSubscriber, [ @purchasable_subscriber ] ]
      
  currency_processor:
    class: %currency_processor.class%
    arguments: [@state, @event_dispatcher]
      
  input_processor_handler:
    calls:
      - [ addProcessor, [ @currency_processor ] ]
      